{% set version = "1.8.9" %}

package:
  name: coin-or-bonmin
  version: {{ version }}

source:
  fn: Bonmin-{{ version }}.tar.gz
  url: https://github.com/coin-or/Bonmin/archive/refs/tags/releases/{{ version }}.tar.gz
  sha256: 8d130430a2776e250e941ee16f51dba301d5f0a00cc288e05f5b985cf1f426cd
  patches:
    - debug.patch

build:
  number: 13
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('coin-or-bonmin', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]

  host:
    - coin-or-cbc
    - ipopt
    - libblas
    - libcblas
    - liblapack

test:
  commands:
    - test -f "${PREFIX}/include/coin/BonTypes.hpp"  # [unix]
    - test -f "${PREFIX}/lib/libbonmin${SHLIB_EXT}"  # [unix]

about:
  home: http://www.coin-or.org/
  license: EPL-1.0
  license_file: LICENSE
  summary: "COIN-OR Basic Open-source Nonlinear Mixed INteger programming"

extra:
  recipe-maintainers:
    - jschueller
