{% set version = "1.8.8" %}

package:
  name: coinbonmin
  version: {{ version }}

source:
  fn: Bonmin-{{ version }}.tgz
  url: https://www.coin-or.org/download/source/Bonmin/Bonmin-{{ version }}.tgz
  sha256: 1a47cf5a4c115974f09d765408ab2116efd4dc1ec13faccd078f2870404316d2

build:
  number: 9
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('coinbonmin', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - make  # [unix]
    - pkg-config  # [unix]
    - coin-or-cbc
    - ipopt
    - libblas
    - libcblas
    - liblapack

test:
  commands:
    - test -f "${PREFIX}/include/coin/BonTypes.hpp"  # [unix]
    - test -f "${PREFIX}/lib/libbonmin${SHLIB_EXT}"  # [unix]

about:
  home: http://www.coin-or.org/
  license: EPL-1.0
  license_file: LICENSE
  summary: "COIN-OR Basic Open-source Nonlinear Mixed INteger programming"

extra:
  recipe-maintainers:
    - jschueller
